travis:
  secure:
    BINSTAR_TOKEN: abrFwtr2CTY3nWz4n3KN1DpQa3sZ37GdD8/UQ9byJsgluPb0RIergOU/zL+2Y4W4I0KAZ5rSjibth/wBVqUF9yv3toF8Dfy3nXb/CCgC5cNhW4PwPxBzDzR7qoL19ye83lrGg0DytLr5n1rRqeVNyfmHHFcG7tLkB9NRlp7vvHwaTnPx9RmMtbleaI2nYB/PeVI4zTEkZFDta1bkMazDPwoJCELBoYytHSe+stsrZqHJoaZb8edeWgt6SYw5SVfz71OW5rKiqbOjmBz0EwuoCiLy9REqgEJxl1L+BKnrY5cEOku0zbZrNMIlrscgm/xDN8LR4ux61faa7I8Z/GmqGf4h4N0T9YLwTQluC8j9Li+TFodTSIgJiGa6Qw/i/833Ef3hexOYZbtyHZj65Z1+TlgQ8XFVO57qQdRzzg0DRnzM7wkT2yxT0ajdVypoieLtoUsAztsvWcgwSiJTpS7+rdv80fiGWT1RryUjMNTun6Jl3cyZWQlOtAvRVLVwetbwkh+bHaZMBx44kxD5ySQykMVIB0O84euZQAR2drPcGlCmKTy+2RLJntUYxRy0UF8Napb2uKEppE5qQSp3cO6czGY8nkxdU2I86zsXjzP5g86GiGjgDFVOjIDIuhrAZiOUyYSQlnQOEpDuqK2+m+E17bRm4k4+7aD/xq01/EcOICo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
